name: Custom-Commands
main: io.github.taixue.plugin.customcommands.CustomCommandPlugin
author: Chuanwise
version: 0.0.1

commands:
  customcommands:
    description: Generic Custom-commands command
    aliases: [ccs]
    usage: /ccs (<config | run> <remain part>)|(reload | debug)
  customcommandsconfig:
    description: Generic Custom-commands command for configuring
    aliases: [ccsc, ccsconfig]
    usage: /ccsc val <variable-name> [set-to]   get or set a variable in config
  customcommandsrun:
    description: Run configured commands
    aliases: [ccsr, ccsrun]
    usage: /ccsr <command-name> [arguments-list]

permissions:
  ccs.*:
    default: op
    description: Give players with op everything by default
    children:
      ccs.run.*: true
  ccs.debug:
    default: op
    description: open or close debug
  ccs.reload:
    default: op
    description: reload all configurations
  ccs.config.val:
    default: op
    children:
      ccs.config.val.set: true
      ccs.config.val.look: true
  ccs.config.val.set:
    default: op
    description: set value of variable in config.yml
  ccs.config.val.look:
    default: op
    description: look value of variable in config.yml

